export const skillGroups = [
  {
    title: "Interface",
    signal: "UI",
    description: "Builds clean responsive interfaces with practical interaction states and modern layouts.",
    barWidth: 88,
    items: [
      "React",
      "JavaScript",
      "TypeScript",
      "jQuery",
      "AJAX",
      "HTML5",
      "CSS3",
      "Bootstrap",
      "Flutter",
      "Framer Motion",
      "GSAP",
    ],
  },
  {
    title: "Application logic",
    signal: "API",
    description: "Connects frontend screens to backend workflows, APIs, access control, and integrations.",
    barWidth: 82,
    items: ["Node.js", "PHP", "CodeIgniter 4", "REST APIs", "API Integration"],
  },
  {
    title: "Data and delivery",
    signal: "DB",
    description: "Structures records, supports reporting, and keeps project data usable across systems.",
    barWidth: 79,
    items: ["MySQL", "PostgreSQL", "Vector Embeddings"],
  },
  {
    title: "Tools and concepts",
    signal: "Tool",
    description: "Uses practical development tools, authentication flows, design systems, and platform basics.",
    barWidth: 75,
    items: [
      "Git",
      "GitHub",
      "Vercel",
      "XAMPP",
      "OAuth 2.0",
      "Gmail API",
      "System Design",
      "Fundamentals of Networking",
      "Figma",
      "WordPress",
    ],
  },
  {
    title: "AI tool proficiency",
    signal: "AI",
    description: "Uses AI tools for prompt engineering, debugging support, and workflow automation.",
    barWidth: 75,
    items: [
      "Codex",
      "ChatGPT",
      "Prompt Engineering",
      "Workflow Automation",
    ],
  },
];

export const skillFlow = [
  "Design UI",
  "Build frontend",
  "Connect backend",
  "Store records",
  "Test workflow",
  "Document proof",
];
